// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Nivl/go-rest-tools/request (interfaces: Response)

// Package mockrequest is a generated GoMock package.
package mockrequest

import (
	gomock "github.com/golang/mock/gomock"
	http "net/http"
	reflect "reflect"
)

// MockResponse is a mock of Response interface
type MockResponse struct {
	ctrl     *gomock.Controller
	recorder *MockResponseMockRecorder
}

// MockResponseMockRecorder is the mock recorder for MockResponse
type MockResponseMockRecorder struct {
	mock *MockResponse
}

// NewMockResponse creates a new mock instance
func NewMockResponse(ctrl *gomock.Controller) *MockResponse {
	mock := &MockResponse{ctrl: ctrl}
	mock.recorder = &MockResponseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockResponse) EXPECT() *MockResponseMockRecorder {
	return m.recorder
}

// Created mocks base method
func (m *MockResponse) Created(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "Created", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Created indicates an expected call of Created
func (mr *MockResponseMockRecorder) Created(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Created", reflect.TypeOf((*MockResponse)(nil).Created), arg0)
}

// Header mocks base method
func (m *MockResponse) Header() http.Header {
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(http.Header)
	return ret0
}

// Header indicates an expected call of Header
func (mr *MockResponseMockRecorder) Header() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockResponse)(nil).Header))
}

// NoContent mocks base method
func (m *MockResponse) NoContent() {
	m.ctrl.Call(m, "NoContent")
}

// NoContent indicates an expected call of NoContent
func (mr *MockResponseMockRecorder) NoContent() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NoContent", reflect.TypeOf((*MockResponse)(nil).NoContent))
}

// Ok mocks base method
func (m *MockResponse) Ok(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "Ok", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ok indicates an expected call of Ok
func (mr *MockResponseMockRecorder) Ok(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ok", reflect.TypeOf((*MockResponse)(nil).Ok), arg0)
}
