// Code generated by mockery v1.0.0
package mockreporter

import mock "github.com/stretchr/testify/mock"
import reporter "github.com/Nivl/go-rest-tools/notifiers/reporter"

// Creator is an autogenerated mock type for the Creator type
type Creator struct {
	mock.Mock
}

// New provides a mock function with given fields:
func (_m *Creator) New() (reporter.Reporter, error) {
	ret := _m.Called()

	var r0 reporter.Reporter
	if rf, ok := ret.Get(0).(func() reporter.Reporter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reporter.Reporter)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
