// Code generated by mockery v1.0.0
package mockreporter

import auth "github.com/Nivl/go-rest-tools/security/auth"
import mock "github.com/stretchr/testify/mock"

// Reporter is an autogenerated mock type for the Reporter type
type Reporter struct {
	mock.Mock
}

// AddTag provides a mock function with given fields: key, value
func (_m *Reporter) AddTag(key string, value string) {
	_m.Called(key, value)
}

// AddTags provides a mock function with given fields: tags
func (_m *Reporter) AddTags(tags map[string]string) {
	_m.Called(tags)
}

// ReportError provides a mock function with given fields: err
func (_m *Reporter) ReportError(err error) {
	_m.Called(err)
}

// ReportErrorAndWait provides a mock function with given fields: err
func (_m *Reporter) ReportErrorAndWait(err error) {
	_m.Called(err)
}

// SetUser provides a mock function with given fields: u
func (_m *Reporter) SetUser(u *auth.User) {
	_m.Called(u)
}
