// Code generated by mockery v1.0.0
package mockrouter

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// HTTPResponse is an autogenerated mock type for the HTTPResponse type
type HTTPResponse struct {
	mock.Mock
}

// Created provides a mock function with given fields: obj
func (_m *HTTPResponse) Created(obj interface{}) error {
	ret := _m.Called(obj)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(obj)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Header provides a mock function with given fields:
func (_m *HTTPResponse) Header() http.Header {
	ret := _m.Called()

	var r0 http.Header
	if rf, ok := ret.Get(0).(func() http.Header); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}

	return r0
}

// NoContent provides a mock function with given fields:
func (_m *HTTPResponse) NoContent() {
	_m.Called()
}

// Ok provides a mock function with given fields: obj
func (_m *HTTPResponse) Ok(obj interface{}) error {
	ret := _m.Called(obj)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(obj)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
