// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Nivl/go-rest-tools/router (interfaces: HTTPRequest)

// Package mockrouter is a generated GoMock package.
package mockrouter

import (
	reflect "reflect"

	go_logger "github.com/Nivl/go-logger"
	go_reporter "github.com/Nivl/go-reporter"
	router "github.com/Nivl/go-rest-tools/router"
	auth "github.com/Nivl/go-rest-tools/security/auth"
	gomock "github.com/golang/mock/gomock"
)

// MockHTTPRequest is a mock of HTTPRequest interface
type MockHTTPRequest struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPRequestMockRecorder
}

// MockHTTPRequestMockRecorder is the mock recorder for MockHTTPRequest
type MockHTTPRequestMockRecorder struct {
	mock *MockHTTPRequest
}

// NewMockHTTPRequest creates a new mock instance
func NewMockHTTPRequest(ctrl *gomock.Controller) *MockHTTPRequest {
	mock := &MockHTTPRequest{ctrl: ctrl}
	mock.recorder = &MockHTTPRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHTTPRequest) EXPECT() *MockHTTPRequestMockRecorder {
	return m.recorder
}

// ID mocks base method
func (m *MockHTTPRequest) ID() string {
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID
func (mr *MockHTTPRequestMockRecorder) ID() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockHTTPRequest)(nil).ID))
}

// Logger mocks base method
func (m *MockHTTPRequest) Logger() go_logger.Logger {
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(go_logger.Logger)
	return ret0
}

// Logger indicates an expected call of Logger
func (mr *MockHTTPRequestMockRecorder) Logger() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockHTTPRequest)(nil).Logger))
}

// Params mocks base method
func (m *MockHTTPRequest) Params() interface{} {
	ret := m.ctrl.Call(m, "Params")
	ret0, _ := ret[0].(interface{})
	return ret0
}

// Params indicates an expected call of Params
func (mr *MockHTTPRequestMockRecorder) Params() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Params", reflect.TypeOf((*MockHTTPRequest)(nil).Params))
}

// Reporter mocks base method
func (m *MockHTTPRequest) Reporter() go_reporter.Reporter {
	ret := m.ctrl.Call(m, "Reporter")
	ret0, _ := ret[0].(go_reporter.Reporter)
	return ret0
}

// Reporter indicates an expected call of Reporter
func (mr *MockHTTPRequestMockRecorder) Reporter() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reporter", reflect.TypeOf((*MockHTTPRequest)(nil).Reporter))
}

// Response mocks base method
func (m *MockHTTPRequest) Response() router.HTTPResponse {
	ret := m.ctrl.Call(m, "Response")
	ret0, _ := ret[0].(router.HTTPResponse)
	return ret0
}

// Response indicates an expected call of Response
func (mr *MockHTTPRequestMockRecorder) Response() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Response", reflect.TypeOf((*MockHTTPRequest)(nil).Response))
}

// Session mocks base method
func (m *MockHTTPRequest) Session() *auth.Session {
	ret := m.ctrl.Call(m, "Session")
	ret0, _ := ret[0].(*auth.Session)
	return ret0
}

// Session indicates an expected call of Session
func (mr *MockHTTPRequestMockRecorder) Session() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Session", reflect.TypeOf((*MockHTTPRequest)(nil).Session))
}

// Signature mocks base method
func (m *MockHTTPRequest) Signature() string {
	ret := m.ctrl.Call(m, "Signature")
	ret0, _ := ret[0].(string)
	return ret0
}

// Signature indicates an expected call of Signature
func (mr *MockHTTPRequestMockRecorder) Signature() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signature", reflect.TypeOf((*MockHTTPRequest)(nil).Signature))
}

// String mocks base method
func (m *MockHTTPRequest) String() string {
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String
func (mr *MockHTTPRequestMockRecorder) String() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockHTTPRequest)(nil).String))
}

// User mocks base method
func (m *MockHTTPRequest) User() *auth.User {
	ret := m.ctrl.Call(m, "User")
	ret0, _ := ret[0].(*auth.User)
	return ret0
}

// User indicates an expected call of User
func (mr *MockHTTPRequestMockRecorder) User() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockHTTPRequest)(nil).User))
}
